server:
 port: 8081
 servlet:
  contex-path: /api	
spring:
 jpa:
  hibernate:
   ddl-auto: create
 datasource:
  url: jdbc:h2:mem:mydb
  path: /h2-console
  username: sa
  password: password
  driver-class-name: org.h2.Driver